### ISSUE TITLE
RCTLinkingManager.h is not found in IOS

### ISSUE THREAD

**Issue by nimabk82** [luisfcofv/react-native-deep-linking#31]
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-native-deep-linking": "^2.1.0",

**Comment by ital0** [comment]
change 

`#import "RCTLinkingManager.h"`

to

`#import <React/RCTLinkingManager.h>`

**Comment by luisfcofv** [comment]
This is not related to this library, closing this issue.
