### ISSUE TITLE
Best practice for catch all route?

### ISSUE THREAD

**Issue by antonmyrberg** [luisfcofv/react-native-deep-linking#37]
Hi, thanks for your efforts with this repo.
Seem really solid!

If I want to catch all routes, especially those that doesn't match specified routes, what's the best way to go about it?

Thanks in advance, Anton

**Comment by luisfcofv** [comment]
Hi @antonmyrberg, thank you!

In that case, I would create a regex to do it. At the moment, routes only support to match specified routes, not ignore them. A regex will do the trick.

Cheers!
