### ISSUE TITLE
does this support deep linking into your app?

### ISSUE THREAD

**Issue by hsavit1** [luisfcofv/react-native-deep-linking#4]
all of the examples show deep linking from your app into another app, for example - like launching facebook. how about deep linking into your own app? does this support that too?

**Comment by luisfcofv** [comment]
Ey @hsavit1, yeah! The Facebook scheme was an example. Try out your own link!

**Add deep link support to your iOS app:** 

**1.-** Make sure you have a URL scheme registered for your app in your Info.plist 
<img width="410" alt="8d913f3e-9a6f-11e4-83a2-49f6564d7a8f" src="https://cloud.githubusercontent.com/assets/1128284/23187470/cc56c8ba-f882-11e6-8bb5-2bdf4a9020bf.png">

**2.-** Add this to your AppDelegate.m

```
#import "RCTLinkingManager.h"

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

// Only if your app is using [Universal Links](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html).
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```

**For Android:**
https://developer.android.com/training/app-indexing/deep-linking.html#adding-filters

More info: https://facebook.github.io/react-native/docs/linking.html

**Comment by hsavit1** [comment]
@luisfcofv thanks for the reply

so I'm still a bit confused. could you possibly add an example to the guide that shows how to handle a deep link into your app?

**Comment by hsavit1** [comment]
what is the difference between a scheme and a route?

**Comment by luisfcofv** [comment]
@hsavit1 I updated the README and the example code, try to run the example provided (Only iOS works at the moment).

When the app is installed,  go to safari and enter a supported deep link into the address bar.
The supported deep links in the example are: `example://test`, `example://test/:id` & `example://test/:id/details`.

Entering the link `example://test/100/details` will open the app.

Hope this is clear enough, let me know how it goes.
Cheers.

**Comment by franj0** [comment]
hello @luisfcofv 

all steps are clear for me, and it's workig in the way is described, but...always but 
I need to send email with link that open my app, and if I in link send prefix as **example://** , the webView not parse link as html... and if I send it without "://" I get link but not opening my app
Pls. help

ty

**Comment by luisfcofv** [comment]
Hi @franj0, this seems more like a format issue with your email app. Have you tried to wrap it in a html hyperlink tag? Something like `<a href="example://route">Open the app</a>`

**Comment by franj0** [comment]
Yes, you are right. Gmail remove href attribute if there exist irl scheeme
e.g. example://....
I have hack solution for this.
Open regular link and on the server side in nginx rewrite do redirect 301
with my url scheme. This is temporary solution until my universal links get
works. Sry for bad eng, ty

**Comment by luisfcofv** [comment]
Great! Glad you figure it out
