### ISSUE TITLE
Reset Scheme Option ?

### ISSUE THREAD

**Issue by ayushnawani** [luisfcofv/react-native-deep-linking#43]
Can we also have reset scheme option? In Android, I am facing an issue where already running app is mounting scenes again on link open request and calling componentDidMount, which is pushing scheme again and causing routes callback to be called multiple times.

So I was hoping there will be some method like below to reset the scheme. Or is there already an option to reset schemes?

`const resetScheme = () => {
  schemes.splice(0, schemes.length);
};`

If this is fine then, I can also send the pull request.

**Comment by luisfcofv** [comment]
There isn't an option to reset schemes unfortunately.
Sure thing. Feel free to send a PR if that solves your problem, I appreciate it.

Cheers

**Comment by ayushnawani** [comment]
Hi @luisfcofv,
I have created the pull request #44 with resetSchemes function. Please review it.

Thanks

**Comment by ayushnawani** [comment]
Thank you @luisfcofv for the quick release.
